sources/BlahBlahBlog/BlahBlahBlog.UI/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;

using BlahBlahBlog.BLL.Data.Transfer;

namespace BlahBlahBlog.UI.Models
{
    /// <summary>
    /// Класс, реализующий модель представления "Домашняя страница".
    /// </summary>
    public class HomeViewModel
    {
        /// <summary>
        /// Статьи, имеющиеся в блоге.
        /// </summary>
        public IEnumerable<DtoPost> Posts { get; set; }

        /// <summary>
        /// Дополнительная информация для пейджинга.
        /// </summary>
        public PagingInfo PagingInfo { get; set; }
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using BlahBlahBlog.UI.Models;

using BlahBlahBlog.BLL.Components.Abstract;

namespace BlahBlahBlog.UI.Controllers
{
    public class HomeController : Controller
    {
        #region Fields

        /// <summary>
        /// Экземпляр сервиса статей.
        /// </summary>
        private IPostService _postService;

        /// <summary>
        /// Количество постов на странице.
        /// </summary>
        public int PageSize { get; set; } = 10;

        #endregion

        #region Constructor

        public HomeController(IPostService postService)
        {
            _postService = postService;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Get-версия метода, реализующая отображение перечня статей с их пейджингом.
        /// </summary>
        /// <param name="pageNumber">Номер текущей страницы.</param>
        [HttpGet]
        public ActionResult Index(int pageNumber = 1)
        {
            var model = new HomeViewModel
            {
                Posts = _postService.All()
                                    .OrderByDescending(p => p.PostDate)
                                    .Skip((pageNumber - 1) * PageSize)
                                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = pageNumber,
                    ItemsPerPage = PageSize,
                    TotalItems = _postService.All().Count()
                }
            };

            return View(model);
        }

        #endregion
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Controllers/PostController.cs
using System;
using System.Web.Mvc;

using AutoMapper;

using BlahBlahBlog.UI.Models;

using BlahBlahBlog.BLL.Components.Abstract;
using BlahBlahBlog.BLL.Data.Transfer;


namespace BlahBlahBlog.UI.Controllers
{
    public class PostController : Controller
    {
        #region Fields

        /// <summary>
        /// Экземпляр сервиса статей.
        /// </summary>
        private IPostService _postService;

        #endregion

        #region Constructor

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Get-версия метода, реализующая вывод требуемой статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Read(int id)
        {
            var model = Mapper.Map<PostViewModel>(_postService.GetById(id));

            return View(model);
        }

        /// <summary>
        /// Get-версия метода, реализующая вызов представления для создания новой статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Post-версия метода, реализующая публикацию новой статьи.
        /// </summary>
        [HttpPost]
        public ActionResult Create(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var post = Mapper.Map<DtoPost>(model);

                _postService.Publish(post);

                return RedirectToAction("Index", "Home", null);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Get-версия метода, реализующая удаление статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Remove(int id)
        {
            _postService.Remove(id);

            return RedirectToAction("Index", "Home", null);
        }

        /// <summary>
        /// Get-версия метода, реализующая вызов представления для редактирования статьи.
        /// </summary>
        [HttpGet]
        public ViewResult Edit(int id)
        {   
            var model = Mapper.Map<PostViewModel>(_postService.GetById(id));

            return View(model);
        }

        /// <summary>
        /// Post-версия метода, реализующая сохранение отредактированной статьи.
        /// </summary>
        [HttpPost]
        public ActionResult Edit(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                _postService.Update(Mapper.Map<DtoPost>(model));

                return RedirectToAction("Index", "Home", null);
            }
            else
            {
                return View();
            }
        }
        
        #endregion
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Views/Home/Index.cshtml
@model BlahBlahBlog.UI.Models.HomeViewModel
@{
    ViewBag.Title = "Домашнаяя страница | BlahBlahBlog";
}

<h1>Список статей</h1>
<div>
    @Html.ActionLink("Добавить новую статью", "Create", "Post")
</div>
@foreach(var post in Model.Posts)
{
    <div>
        <div>
            <h2>@post.PostTitle</h2>
            <p>Опубликовано: @post.PostDate</p>
            <div>

            </div>
                @Html.ActionLink("Редактировать", "Edit", "Post", new { id = post.PostId }, null) | 
                @Html.ActionLink("Удалить", "Remove", "Post", new { id = post.PostId }, null)
            </div>
        </div>
        <div>@post.PostExcerpt</div>
    <div>
       <a href="/Post/Read/@post.PostId">Читать далее..</a>
    </div>  
}

@*<div class="pager">
    @Html.GeneratePageLinks(Model.PagingInfo, n => Url.Action("Index", new { pageNumber = n }))
</div>*@

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@