sources/BlahBlahBlog/BlahBlahBlog.UI/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BlahBlahBlog.UI.Models
{
    /// <summary>
    /// Модель представления работы со статьей.
    /// </summary>
    public class PostViewModel
    {
        /// <summary>
        /// Код статьи.
        /// </summary>
        public int PostId { get; set; }

        /// <summary>
        /// Заголовок статьи.
        /// </summary>
        [Display(Name = "Заголовок статьи")]
        [Required(ErrorMessage = "Заголовок статьи должен быть указан.")]
        [MaxLength(100, ErrorMessage = "Длина заголовка статьи не должна превышать 100 символов!")]
        public string PostTitle { get; set; }

        /// <summary>
        /// Текст статьи.
        /// </summary>
        [AllowHtml]
        [UIHint("tinymce_full_compressed")]
        [Display(Name = "Текст статьи")]
        [Required(ErrorMessage = "Текст статьи должен быть указан.")]
        public string PostContent { get; set; }

        /// <summary>
        /// Краткое содержание статьи.
        /// </summary>
        [Display(Name = "Краткое содержание")]
        [Required(ErrorMessage = "Крактое содержание статьи должно быть указано.")]
        [MaxLength(255, ErrorMessage = "Длина заголовка статьи не должна превышать 255 символов!")]
        public string PostExcerpt { get; set; }

        /// <summary>
        /// Дата публикации статьи.
        /// </summary>
        [DataType(DataType.DateTime)]
        public DateTime PostDate { get; set; }

        public List<CommentViewModel> Comments { get; set; }
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Controllers/CommentController.cs
using System.Web.Mvc;

using AutoMapper;

using BlahBlahBlog.UI.Models;

using BlahBlahBlog.BLL.Components.Abstract;
using BlahBlahBlog.BLL.Data.Transfer;

namespace BlahBlahBlog.UI.Controllers
{
    public class CommentController : Controller
    {
        #region Fields

        /// <summary>
        /// Экземляр сервиса комментариев.
        /// </summary>
        private ICommentService _commentService;

        #endregion


        #region Constructor

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }
       
        #endregion
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult Create(int postId)
        {
            var model = new CommentViewModel { PostId = postId };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CommentViewModel model)
        {
            var comment = Mapper.Map<DtoComment>(model);

            _commentService.Add(comment);

            return RedirectToAction("Read", "Post", new { id = comment.PostId });
        }
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Controllers/PostController.cs
using System;
using System.Web.Mvc;

using AutoMapper;

using BlahBlahBlog.UI.Models;

using BlahBlahBlog.BLL.Components.Abstract;
using BlahBlahBlog.BLL.Data.Transfer;


namespace BlahBlahBlog.UI.Controllers
{
    public class PostController : Controller
    {
        #region Fields

        /// <summary>
        /// Экземпляр сервиса статей.
        /// </summary>
        private IPostService _postService;

        #endregion

        #region Constructor

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Get-версия метода, реализующая вывод требуемой статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Read(int id)
        {
            var model = Mapper.Map<PostViewModel>(_postService.GetById(id));

            return View(model);
        }

        /// <summary>
        /// Get-версия метода, реализующая вызов представления для создания новой статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Post-версия метода, реализующая публикацию новой статьи.
        /// </summary>
        [HttpPost]
        public ActionResult Create(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var post = Mapper.Map<DtoPost>(model);

                _postService.Publish(post);

                return RedirectToAction("Index", "Home", null);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// Get-версия метода, реализующая удаление статьи.
        /// </summary>
        [HttpGet]
        public ActionResult Remove(int id)
        {
            _postService.Remove(id);

            return RedirectToAction("Index", "Home", null);
        }

        /// <summary>
        /// Get-версия метода, реализующая вызов представления для редактирования статьи.
        /// </summary>
        [HttpGet]
        public ViewResult Edit(int id)
        {   
            var model = Mapper.Map<PostViewModel>(_postService.GetById(id));

            return View(model);
        }

        /// <summary>
        /// Post-версия метода, реализующая сохранение отредактированной статьи.
        /// </summary>
        [HttpPost]
        public ActionResult Edit(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                _postService.Update(Mapper.Map<DtoPost>(model));

                return RedirectToAction("Index", "Home", null);
            }
            else
            {
                return View();
            }
        }
        
        #endregion
    }
}

sources/BlahBlahBlog/BlahBlahBlog.UI/Views/Post/Create.cshtml
@model BlahBlahBlog.UI.Models.PostViewModel

@{
    ViewBag.Title = "Добавление новой статьи";
}
<h2>CreatePost</h2>
<fieldset>
    @using (Html.BeginForm())
    {
        <legend>Добавление новой статьи</legend>
            
        @Html.ValidationSummary()
          
        <div class="editor-label">
            @Html.LabelFor(m => m.PostTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.PostTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.PostExcerpt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.PostExcerpt)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.PostContent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.PostContent)
        </div>

        <br />
        <input type="submit" value="Опубликовать" />
    }
</fieldset>

sources/BlahBlahBlog/BlahBlahBlog.UI/Views/Post/Edit.cshtml
@model BlahBlahBlog.UI.Models.PostViewModel

@{
    ViewBag.Title = "Редактирование статьи";
}

<html>
<body>
    <fieldset>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary();
            @Html.AntiForgeryToken();

            <legend>Редактирование статьи</legend>
            @Html.HiddenFor(m => m.PostId)
            <div class="editor-label">
                @Html.LabelFor(m => m.PostTitle)
            </div>
            <div class="editor-field">
                @Html.EditorFor(m => m.PostTitle)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.PostExcerpt)
            </div>
            <div class="editor-field">
                @Html.EditorFor(m => m.PostExcerpt)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.PostContent)
            </div>
            <div class="editor-field">
                @Html.EditorFor(m => m.PostContent)
            </div>
            <input type="submit" value="Опубликовать" />
        }
        </fieldset>
</body>
</html>

sources/BlahBlahBlog/BlahBlahBlog.UI/Views/Post/Read.cshtml
@model BlahBlahBlog.UI.Models.PostViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.PostTitle | Blah-Blah Blog</title>
</head>
<body>
    <div> 
        <h1>@Model.PostTitle</h1>
        <div>Обубликовано: @Model.PostDate</div>
        <div>@Html.Raw(Server.HtmlDecode(Model.PostContent))</div>

        @if(Model.Comments.Count() > 0)
        {
            @Html.Partial("~/Views/Comment/Index.cshtml", Model.Comments);
        }
        @{ Html.RenderAction("Create", "Comment", new { postId = Model.PostId }); }
    </div>
</body>
</html>